### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by gazzastone** [mvmn/gp2srv#3]
Hi this looks a great project but as a total newbie to Rasberry PI and for that matter Linux do you have a step by step guide for installing the latest version

many thanks

Gary

**Comment by mvmn** [comment]
Hi
There is no instruction at the moment, unfortunately. I'll create one later.

For now, please do this:
- Install latest Raspbian (Jessie) onto SD card
  See https://www.raspberrypi.org/documentation/installation/installing-images/
  Do all the usual configs after installation (run raspi-config and do expand filesystem, change hostname/password if you wish, etc).
- If you want Raspberry Pi to provide WiFi (which you probably do want in order to use GPhoto2Server outdoors, and not carry around some sort of battery powered WiFi router) - use Adafruit instructions on how to do that:
  https://learn.adafruit.com/setting-up-a-raspberry-pi-as-a-wifi-access-point/overview
  This step is a bit hard though, and you need to have a good WiFi dongle (one that supports infrastructure mode). Thus if it is not entirely necessary - skip it. 
  Or you can do this after other steps - it does not necessarily have to be done as step 2.
- On your Raspberry Pi run gphoto2-updater in order to have latest libgphoto2 installed:
  https://github.com/gonzalo/gphoto2-updater#how-to-use
- Download latest GPhoto2Server release (currently it's 1.2 - https://github.com/mvmn/gp2srv/releases/download/1.2/gp2srv-1.2.zip ) onto your Raspberry Pi. Unzip it.
- When you need to use GPhoto2Server - plug your camera into Raspberry Pi via USB (before starting GPhoto2Server) and execute this command in terminal in folder to which you have unzipped `gp2srv-<version>.zip` in order to start GPhoto2Server:

`java -jar GPhoto2Server-<version>.jar`
- Connect to same network where Raspberry Pi is (WiFi or whatever you have), and in a web browser open URL `http://<your Raspberry Pi IP address or hostname.local>:8080`

There you should have GPhoto2Server working.

**Comment by mvmn** [comment]
Created a Wiki page:
https://github.com/mvmn/gp2srv/wiki/Installation-to-Raspberry-Pi
