### ISSUE TITLE
Java 1.6 compatibility

### ISSUE THREAD

**Issue by spectrared** [mvmn/gp2srv#9]
Might not be an error..  From the downloaded jar file I am getting major.minor version errors when I try to run the jar.  This is on Java 1.6, the last 32 bit version for the core duo macs (so I cannot really upgrade to Java 7 or later). New to Java, so I'm not sure, I may have other configuration errors, but should the pre-built downloads work on 32 bit OS x 10.6.8? I can copy over the relevant console portions if helpful.

**Comment by mvmn** [comment]
The problem is with the Java version - you need Java 1.8+ to run GPhoto2Server.

I've kept my code Java 1.5+ compatible, but I'm using WebSockets, and that requires Servlet API3.1 (which requires Java 1.7+) and Jetty Server version 9+ (which requires Java 1.8+).

Unfortunately, I can't easily work around this. I can try to separate WebSocket dependent logic so it would conditionally load if you have Jetty 9 (and thus Java 1.8+), but I'm not sure how easy this will be.

Or maybe I'll just make a branch without WebSockets support and make a build of that for you.

Meanwhile, if there is any way you can get Java 1.8 installed though (maybe using a hack like [this one](http://jksha.blogspot.se/2013/09/java-7-and-snow-leopard-osx-106.html) to trick the Java installer into not checking OS X version, or maybe you could try building OpenJDK from source) - please try that for now.

**Comment by spectrared** [comment]
Thank you for the quick response.

Unfortunately, this laptop is a Core Duo, which is a 32 bit processor.  As a result it will not run a 64 bit version of Java, and that is all that I can find pre-compiled for OS X from Oracle or Apple.  The OpenJDK project has new versions to build, but they are also 64 bit only on OS X.  So I believe I am stuck.

I may try installing a Linux partition on the laptop, as there are 32 bit JDKs in that ecosystem.

Thanks again for your quick response.  I have a newer desktop system (OS X Sierra) and will be trying your product there.  This is a very nice package (if I could get it working..)

**Comment by mvmn** [comment]
You owe me dude ;-)
https://github.com/mvmn/gp2srv/releases/tag/J5_2.7
